general {
  after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({action = "on"})'

  ignore_dbus_inhibit = 1
  ignore_wayland_inhibit = 1
  ignore_systemd_inhibit = 1

  inhibit_sleep = 0
}

listener {
  timeout = 300
  on-timeout = brightnessctl -s set 10000
  on-resume = brightnessctl -r
}

listener {
  timeout = 350
  on-timeout = hyprctl dispatch 'hl.dsp.dpms({action = "off"})'
  on-resume = hyprctl dispatch 'hl.dsp.dpms({action = "on"})'
}

listener {
  timeout = 500
  on-timeout = loginctl suspend
}
