general {
  lock_cmd = pidof desklock || desklock
  before_sleep_cmd = loginctl lock-session
  after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({action = "on"})'
  inhibit_sleep = 0
}

listener {
  timeout = 300
  on-timeout = brightnessctl -s set 10000
  on-resume = brightnessctl -r
}

listener {
  timeout = 500
  on-timeout = hyprctl dispatch 'hl.dsp.dpms({action = "off"})'
  on-resume = hyprctl dispatch 'hl.dsp.dpms({action = "on"})'
}

listener {
  timeout = 600
  on-timeout = loginctl suspend
}
